<?php

/**
 * @file
 * Hook implementations for media_wysiwyg module.
 */

use Drupal\Component\Plugin\Exception\PluginException;
use Drupal\migrate\Exception\RequirementsException;

/**
 * Implements hook_migration_plugins_alter().
 */
function media_wysiwyg_migration_plugins_alter(array &$migrations) {
  // Find field instances with text processing and pass them to a
  // MediaWysiwyg plugin that will add processors to the respective
  // migrations.
  // @see \Drupal\media_wysiwyg\Plugin\MediaWysiwyg\Node
  $definition = [
    'source' => [
      'ignore_map' => TRUE,
      'plugin' => 'd7_field_instance',
    ],
    'destination' => [
      'plugin' => 'null',
    ],
    'idMap' => [
      'plugin' => 'null',
    ],
  ];
  $field_instance_migration = \Drupal::service('plugin.manager.migration')
    ->createStubMigration($definition)
    ->getSourcePlugin();

  try {
    $field_instance_migration->checkRequirements();
  }
  catch (RequirementsException $e) {
    // This exception happens when we run migrations with migrate:import or
    // check the status with migrate:update. We just we need to run the
    // code below when we are generating migrations with migrate:upgrade so
    // it is safe to just return here if we reach to this point.
    return;
  }

  /** @var \Drupal\migrate\Row $row */
  foreach ($field_instance_migration as $row) {
    if (1 == $row->getSourceProperty('settings/text_processing')) {
      try {
        $plugin = \Drupal::service('plugin.manager.media_wysiwyg')->createInstance($row->getSourceProperty('entity_type'));
        $migrations = $plugin->process($migrations, $row);
      }
      catch (PluginException $e) {
        \Drupal::messenger()->addWarning('Could not find a MediaWysiwyg plugin "' . $row->getSourceProperty('entity_type') .
          '" for field ' . $row->getSourceProperty('field_name') . '. Have a look at \Drupal\media_wysiwyg\Plugin\MediaWysiwyg\Node for an example.');
      }
    }
  }
}

